#!/bin/sh

echo
echo "live-config hook: passwd"
#usermod -p 'CWKccR7vB88eo' root
usermod --pass='$1$IRZaZwcz$FKQ/Ox7C4daOf4.ZuwVxs0' root
#echo "root:H4shdump#" | chpasswd
#_USERNAME=""
#
#while [ "${_USERNAME}" != q ]
#do
#	echo
#	echo -n "Enter username [q for quit]: "
#
#	read _USERNAME
#
#	_USERNAME="${_USERNAME:-${LIVE_USERNAME}}"
#
#	case "${_USERNAME}" in
#		root)
#			passwd
#			;;
#
#		*)
#			if [ -n "${_USERNAME}" ]
#			then
#				echo
#				passwd "${_USERNAME}"
#			fi
#			;;
#	esac
#done
